from django.urls import path
from stocksales.api import views
from rest_framework.authtoken.views import obtain_auth_token

app_name = 'adminstration'

urlpatterns = [
    path('reg_phone_type', views.reg_phone_type,
         name='reg_phone_type'),
    path('reg_brand', views.reg_brand,
         name='reg_brand'),
    path('reg_phone_model', views.reg_phone_model,
         name='reg_phone_model'),
    path('reg_color', views.reg_color,
         name='reg_color'),
    path('reg_storage', views.reg_storage,
         name='reg_storage'),
    path('product_stock_in', views.product_stock_in,
         name='product_stock_in'),
    path('shop_product', views.shop_product,
         name='shop_product'),
    path('stock_admin', views.stock_admin,
         name='stock_admin'),
    # not really neccessary
    path('viewing_stock_in_product', views.viewing_stock_in_product,
         name='viewing_stock_in_product'),
    path('get_sales_details', views.get_sales_details,
         name='get_sales_details'),
    path('get_stock_to_shop_dtls', views.get_stock_to_shop_dtls,
         name='get_stock_to_shop_dtls'),
    path('get_stock_in_details', views.get_stock_in_details,
         name='get_stock_in_details'),
    path('get_stock_in_by_brand', views.get_stock_in_by_brand,
         name='get_stock_in_by_brand'),
    path('get_product_details', views.get_product_details,
         name='get_product_details'),
    path('move_stock_to_shop', views.move_stock_to_shop,
         name='move_stock_to_shop'),
    path('get_shop_product', views.get_shop_product,
         name='get_shop_product'),
    path('get_shop_product_by_brand', views.get_shop_product_by_brand,
         name='get_shop_product_by_brand'),
    path('get_shop_product_by_model', views.get_shop_product_by_model,
         name='get_shop_product_by_model'),
    path('get_shop_product_by_imei', views.get_shop_product_by_imei,
         name='get_shop_product_by_imei'),
    path('recieve_product_by_imei', views.recieve_product_by_imei,
         name='recieve_product_by_imei'),
    path('sale_product', views.sale_product,
         name='sale_product'),
    path('get_sale_product', views.get_sale_product,
         name='get_sale_product'),
    path('get_sales_by_brand', views.get_sales_by_brand,
         name='get_sales_by_brand'),
    path('sales_model_details', views.sales_model_details,
         name='sales_model_details'),
    path('stock_in_details_by_model', views.stock_in_details_by_model,
         name='stock_in_details_by_model'),
]
