# Generated by Django 3.1.2 on 2020-11-26 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminstration', '0002_usershopassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=100)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'color',
            },
        ),
        migrations.CreateModel(
            name='PhoneModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=60)),
                ('processor', models.CharField(max_length=60)),
                ('ram', models.CharField(max_length=60)),
                ('camera_front', models.CharField(max_length=60)),
                ('camera_back', models.CharField(max_length=60)),
                ('screen_size', models.CharField(max_length=60)),
                ('screen_resolution', models.CharField(max_length=60)),
                ('battery_life', models.CharField(max_length=60)),
                ('battery_type', models.CharField(max_length=60)),
                ('operating_system', models.CharField(max_length=60)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stocksales.brand')),
            ],
            options={
                'db_table': 'phone_model',
            },
        ),
        migrations.CreateModel(
            name='PhoneType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'phone_type',
            },
        ),
        migrations.CreateModel(
            name='ProductStockIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buying_price', models.CharField(max_length=60)),
                ('selling_price', models.CharField(max_length=60)),
                ('timestamp_in', models.DateField(auto_now_add=True)),
                ('timestamp_out', models.DateField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stocksales.brand')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stocksales.color')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stocksales.phonetype')),
                ('phone_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stocksales.phonemodel')),
            ],
            options={
                'db_table': 'product_stock_in',
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_size', models.CharField(max_length=100)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'storage',
            },
        ),
        migrations.CreateModel(
            name='StockToShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('product_stock_in', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stocksales.productstockin')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminstration.shop')),
            ],
            options={
                'db_table': 'stock_to_shop',
            },
        ),
        migrations.CreateModel(
            name='ShopToShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('product_stock_in', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stocksales.productstockin')),
                ('shop_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shop_from', to='adminstration.shop')),
                ('shop_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shop_to', to='adminstration.shop')),
            ],
            options={
                'db_table': 'shop_to_shop',
            },
        ),
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('product_stock_in', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stocksales.productstockin')),
                ('shop_available', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminstration.shop')),
            ],
            options={
                'db_table': 'shop_product',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.CharField(max_length=20)),
                ('markup', models.CharField(max_length=20)),
                ('actual_selling_price', models.CharField(max_length=20)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('product_stock_in', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stocksales.productstockin')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminstration.shop')),
            ],
            options={
                'db_table': 'sales',
            },
        ),
        migrations.AddField(
            model_name='productstockin',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stocksales.storage'),
        ),
        migrations.AddField(
            model_name='productstockin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stocksales.phonetype'),
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brand',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stocksales.phonetype'),
        ),
    ]
